name: Deploy NuGet Packages

on:
  workflow_dispatch:

jobs:
  deploy:
    name: 🚀 Publish Packages
    runs-on: windows-latest
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v2

      - name: ✨ Setup .NET 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: 🛠️ Setup NuGet
        uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}

      - name: 🚀 Publish ScottPlot
        run: |
          dotnet restore src/ScottPlot4/ScottPlot/ScottPlot.csproj
          dotnet build src/ScottPlot4/ScottPlot/ScottPlot.csproj --configuration Release
          dotnet pack src/ScottPlot4/ScottPlot/ScottPlot.csproj --configuration Release
          nuget push "src\ScottPlot4\ScottPlot\bin\Release\*.nupkg" -SkipDuplicate -Source https://api.nuget.org/v3/index.json

      - name: 🚀 Publish ScottPlot.WinForms
        run: |
          dotnet restore src/ScottPlot4/ScottPlot.WinForms/ScottPlot.WinForms.NUGET.csproj
          dotnet build src/ScottPlot4/ScottPlot.WinForms/ScottPlot.WinForms.NUGET.csproj --configuration Release
          dotnet pack src/ScottPlot4/ScottPlot.WinForms/ScottPlot.WinForms.NUGET.csproj --configuration Release
          nuget push "src\ScottPlot4\ScottPlot.WinForms\bin\Release\*.nupkg" -SkipDuplicate -Source https://api.nuget.org/v3/index.json

      - name: 🚀 Publish ScottPlot.WPF
        run: |
          dotnet restore src/ScottPlot4/ScottPlot.WPF/ScottPlot.WPF.NUGET.csproj
          dotnet build src/ScottPlot4/ScottPlot.WPF/ScottPlot.WPF.NUGET.csproj --configuration Release
          dotnet pack src/ScottPlot4/ScottPlot.WPF/ScottPlot.WPF.NUGET.csproj --configuration Release
          nuget push "src\ScottPlot4\ScottPlot.WPF\bin\Release\*.nupkg" -SkipDuplicate -Source https://api.nuget.org/v3/index.json

      - name: 🚀 Publish ScottPlot.Avalonia
        run: |
          dotnet restore src/ScottPlot4/ScottPlot.Avalonia/ScottPlot.Avalonia.NUGET.csproj
          dotnet build src/ScottPlot4/ScottPlot.Avalonia/ScottPlot.Avalonia.NUGET.csproj --configuration Release
          dotnet pack src/ScottPlot4/ScottPlot.Avalonia/ScottPlot.Avalonia.NUGET.csproj --configuration Release
          nuget push "src\ScottPlot4\ScottPlot.Avalonia\bin\Release\*.nupkg" -SkipDuplicate -Source https://api.nuget.org/v3/index.json

      - name: 🚀 Publish ScottPlot.Eto
        run: |
          dotnet restore src/ScottPlot4/ScottPlot.Eto/ScottPlot.Eto.NUGET.csproj
          dotnet build src/ScottPlot4/ScottPlot.Eto/ScottPlot.Eto.NUGET.csproj --configuration Release
          dotnet pack src/ScottPlot4/ScottPlot.Eto/ScottPlot.Eto.NUGET.csproj --configuration Release
          nuget push "src\ScottPlot4\ScottPlot.Eto\bin\Release\*.nupkg" -SkipDuplicate -Source https://api.nuget.org/v3/index.json

      - name: 💾 Store Packages
        uses: actions/upload-artifact@v2
        with:
          name: ScottPlot-Packages
          retention-days: 1
          path: |
            src/ScottPlot4/ScottPlot/bin/Release/*.nupkg
            src/ScottPlot4/ScottPlot/bin/Release/*.snupkg
            src/ScottPlot4/ScottPlot.WinForms/bin/Release/*.nupkg
            src/ScottPlot4/ScottPlot.WinForms/bin/Release/*.snupkg
            src/ScottPlot4/ScottPlot.WPF/bin/Release/*.nupkg
            src/ScottPlot4/ScottPlot.WPF/bin/Release/*.snupkg
            src/ScottPlot4/ScottPlot.Avalonia/bin/Release/*.nupkg
            src/ScottPlot4/ScottPlot.Avalonia/bin/Release/*.snupkg
            src/ScottPlot4/ScottPlot.Eto/bin/Release/*.nupkg
            src/ScottPlot4/ScottPlot.Eto/bin/Release/*.snupkg
